package com.dicka.springboot.entity;
// Generated Mar 31, 2017 6:54:57 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name="account"
    ,catalog="db_hibernate"
)
public class Account  implements java.io.Serializable {


     private String username;
     private String password;
     private String fullname;
     private Set<Transaksi> transaksis = new HashSet<Transaksi>(0);

    public Account() {
    }

	
    public Account(String username, String password, String fullname) {
        this.username = username;
        this.password = password;
        this.fullname = fullname;
    }
    public Account(String username, String password, String fullname, Set<Transaksi> transaksis) {
       this.username = username;
       this.password = password;
       this.fullname = fullname;
       this.transaksis = transaksis;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false, length=100)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=100)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="fullname", nullable=false, length=100)
    public String getFullname() {
        return this.fullname;
    }
    
    public void setFullname(String fullname) {
        this.fullname = fullname;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="account")
    public Set<Transaksi> getTransaksis() {
        return this.transaksis;
    }
    
    public void setTransaksis(Set<Transaksi> transaksis) {
        this.transaksis = transaksis;
    }




}


