package com.dicka.springboot.entity;
// Generated Mar 31, 2017 6:54:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Barang generated by hbm2java
 */
@Entity
@Table(name="barang"
    ,catalog="db_hibernate"
)
public class Barang  implements java.io.Serializable {


     private String idbarang;
     private Kategori kategori;
     private String nama;
     private int jumlah;
     private BigDecimal harga;
     private String fileName;
     private byte[] fileData;
     private Set<TransaksiDetil> transaksiDetils = new HashSet<TransaksiDetil>(0);

    public Barang() {
    }

	
    public Barang(String idbarang, Kategori kategori, String nama, int jumlah, BigDecimal harga, String fileName, byte[] fileData) {
        this.idbarang = idbarang;
        this.kategori = kategori;
        this.nama = nama;
        this.jumlah = jumlah;
        this.harga = harga;
        this.fileName = fileName;
        this.fileData = fileData;
    }
    public Barang(String idbarang, Kategori kategori, String nama, int jumlah, BigDecimal harga, String fileName, byte[] fileData, Set<TransaksiDetil> transaksiDetils) {
       this.idbarang = idbarang;
       this.kategori = kategori;
       this.nama = nama;
       this.jumlah = jumlah;
       this.harga = harga;
       this.fileName = fileName;
       this.fileData = fileData;
       this.transaksiDetils = transaksiDetils;
    }
   
     @Id 

    
    @Column(name="idbarang", unique=true, nullable=false, length=12)
    public String getIdbarang() {
        return this.idbarang;
    }
    
    public void setIdbarang(String idbarang) {
        this.idbarang = idbarang;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idkategori", nullable=false)
    public Kategori getKategori() {
        return this.kategori;
    }
    
    public void setKategori(Kategori kategori) {
        this.kategori = kategori;
    }

    
    @Column(name="nama", nullable=false, length=45)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }

    
    @Column(name="jumlah", nullable=false)
    public int getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(int jumlah) {
        this.jumlah = jumlah;
    }

    
    @Column(name="harga", nullable=false, precision=6, scale=3)
    public BigDecimal getHarga() {
        return this.harga;
    }
    
    public void setHarga(BigDecimal harga) {
        this.harga = harga;
    }

    
    @Column(name="file_name", nullable=false, length=130)
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    
    @Column(name="file_data", nullable=false)
    public byte[] getFileData() {
        return this.fileData;
    }
    
    public void setFileData(byte[] fileData) {
        this.fileData = fileData;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="barang")
    public Set<TransaksiDetil> getTransaksiDetils() {
        return this.transaksiDetils;
    }
    
    public void setTransaksiDetils(Set<TransaksiDetil> transaksiDetils) {
        this.transaksiDetils = transaksiDetils;
    }




}


