package com.dicka.springboot.entity;
// Generated Mar 31, 2017 6:54:57 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TransaksiDetilId generated by hbm2java
 */
@Embeddable
public class TransaksiDetilId  implements java.io.Serializable {


     private int idtransaksi;
     private String idbarang;

    public TransaksiDetilId() {
    }

    public TransaksiDetilId(int idtransaksi, String idbarang) {
       this.idtransaksi = idtransaksi;
       this.idbarang = idbarang;
    }
   


    @Column(name="idtransaksi", nullable=false)
    public int getIdtransaksi() {
        return this.idtransaksi;
    }
    
    public void setIdtransaksi(int idtransaksi) {
        this.idtransaksi = idtransaksi;
    }


    @Column(name="idbarang", nullable=false, length=12)
    public String getIdbarang() {
        return this.idbarang;
    }
    
    public void setIdbarang(String idbarang) {
        this.idbarang = idbarang;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TransaksiDetilId) ) return false;
		 TransaksiDetilId castOther = ( TransaksiDetilId ) other; 
         
		 return (this.getIdtransaksi()==castOther.getIdtransaksi())
 && ( (this.getIdbarang()==castOther.getIdbarang()) || ( this.getIdbarang()!=null && castOther.getIdbarang()!=null && this.getIdbarang().equals(castOther.getIdbarang()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdtransaksi();
         result = 37 * result + ( getIdbarang() == null ? 0 : this.getIdbarang().hashCode() );
         return result;
   }   


}


